services:
  api:
    env_file: ./.env
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  db:
    image: postgres:16.4
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    # apiが起動する前にDBが起動していないとエラーになるためhealthcheckをする
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db: